apiVersion: v2
name: ipam
description: IPAM - IP Address Management for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ipam
  - ip-address-management
maintainers: []

dependencies:
  - name: postgresql
    version: "18.3.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
