{{- if and .Values.database .Values.database.url (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipam.fullname" . }}-db
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.database.url | quote }}
{{- end }}
