{{- if and .Values.postgresql.enabled (not .Values.existingSecret) (not (and .Values.database .Values.database.url)) }}
{{- $user := default "postgres" .Values.postgresql.auth.username }}
{{- $db := default "ipam" .Values.postgresql.auth.database }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipam.fullname" . }}-postgresql-url
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgresql://{{ $user }}:{{ if .Values.postgresql.auth.username }}{{ .Values.postgresql.auth.password | urlquery }}{{ else }}{{ .Values.postgresql.auth.postgresPassword | urlquery }}{{ end }}@{{ .Release.Name }}-postgresql:5432/{{ $db }}?sslmode=disable"
{{- end }}
